config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :recipes do
      resources :ingredients do
        member do
           patch :shopping_toggle
        end
      end
    end
  root "recipes#index"
  # get '/search' => 'recipes#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

  validates :name, presence: true, uniqueness: true
  validates :qty, numericality: { only_integer: true }, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :delete_all
    belongs_to :user
    def start_time 
        self.when
    end

    validates :name, presence: true, uniqueness: true
    validates :time, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recipes
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    before_action :set_recipe 
    before_action :set_ingredient, except: [:create]

    def index
        @ingredients = Ingredient.all
    end

    def create 
        @ingredient = @recipe.ingredients.create(ingredient_params)
        redirect_to  @recipe
    end

    def destroy
        @ingredient = @recipe.ingredients.find(params[:id])
        if @ingredient.destroy
            flash[:success] = "Ingredient was destroyed."
        else
            flash[:error] = "Ingredient could not be destroyed."
        end
        redirect_to @recipe
    end

    def shopping_toggle
        if @ingredient.shopping == false
            @ingredient.update_attribute(:shopping, true)
        else 
            @ingredient.update_attribute(:shopping, false)
        end
        redirect_to @recipe
    end

    private

    def set_recipe
        @recipe = Recipe.find(params[:recipe_id])
    end

    def set_ingredient
        @ingredient = @recipe.ingredients.find(params[:id])
    end

    def ingredient_params
        params[:ingredient].permit(:name, :qty, :unit, :shopping)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show
  end


  def new
    @recipe = Recipe.new
  end


  def edit
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def search
  #   recipes = find_recipe(params[:recipe])
  #   unless recipes
  #     flash[:alert] = 'Recipe not found'
  #     return render action: :index
  #   end
  # end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :description, :time, :when)
    end

    # def request_api(url)
    #   response = Excon.get(
    #     url,
    #     headers: {
    #       'X-RapidAPI-Host' => URI.parse(url).host,
    #       'X-RapidAPI-Key' => ENV['RAPIDAPI_API_KEY']
    #     }
    #   )
    #   return nil if response.status != 200
    #   JSON.parse(response.body)
    # end

    # def find_recipe(name)
    #   request_api("https://edamam-recipe-search.p.rapidapi.com/search?q=#{URI.encode(name)}")
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/ingredients/_form.html.erb
<%= bootstrap_form_for([@recipe, @recipe.ingredients.build]) do |f| %>
 <%= f.label "Add ingredients:" %>
 <%= f.text_field :name, placeholder: "New Ingredient" %>
 <%= f.text_field :qty, placeholder: "Quantity" %>
 <%= f.text_field :unit, placeholder: "Unit" %>
 <%= f.submit %>
<% end %>

app/views/ingredients/_ingredient.html.erb
<link rel="stylesheet" href="ingredients.scss">

<p><%= "#{ingredient.name} #{ingredient.qty} #{ingredient.unit}" %>
<%= link_to "Delete", recipe_ingredient_path(@recipe, ingredient.id), method: :delete, data: { confirm: "Are you sure?" }, :class => "btn btn-outline-success" %>
<% if ingredient.shopping == false%>
    <%= link_to "Add to Shopping List", shopping_toggle_recipe_ingredient_path(@recipe, ingredient.id),method: :patch, :class => "btn btn-outline-success" %>
<% else %>
    <%= link_to "Remove from Shopping List", shopping_toggle_recipe_ingredient_path(@recipe, ingredient.id),method: :patch, :class => "btn btn-outline-success" %>
<%end%>    
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipePlanner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <footer>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>


  <body>
    <nav class="navbar fixed-top navbar-dark bg-dark">
      <div class="navbar-inner">
      <a class="navbar-brand" href="/">Nookbook</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse w-100 order-3 dual-collapse2" id="navbarSupportedContent" >
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
           <p class="navbar-text float-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
              <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
          </li>
        </ul>   
      </div>
    </div>
  </nav>
    
    
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= bootstrap_form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.text_field :description %>
  </div>

  <div class="form-group">
    <%= form.number_field :time %>
  </div>

  <div class="form-group">
    <%= form.date_field :when %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path, :class => "btn btn-outline-success" %>

app/views/recipes/index.html.erb
<h1>My Recipes</h1>

<br>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Time (in minutes)</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
    
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.description %></td>
        <td><%= recipe.time %></td>
        <td><%= recipe.when %></td>
        <td><%= link_to 'Show Details', recipe, :class => "btn btn-outline-success" %></td>
        <td><%= link_to 'Edit Recipe', edit_recipe_path(recipe), :class => "btn btn-outline-success" %></td>
        <td><%= link_to 'Destroy Recipe', recipe, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-success" %></td>
      </tr>
    <% end %>
    
  </tbody>
  
  
</table>

<br>

<div>
<%= link_to 'New Recipe', new_recipe_path, :class => "btn btn-outline-success" %>
</div>

<br>

<%
=begin%>
 <div class="col-lg-12 mt-5">
  <% if flash[:alert] %>
    <div class="alert alert-warning"><%= flash[:alert] %></div>
  <% end %>
  <div class="mx-auto mt-5" style="width: 400px">
      <%= form_with(url: search_path, method: 'get', local: true) do %>
         <div class="form-group">
            <%= label_tag :recipe, 'Search for a recipe '%>
            <%= text_field_tag :recipe, nil, placeholder: 'Eg. chocolate', class: 'form-control' %>
         </div>
      <%= button_tag 'Search', class: 'btn btn-success btn-block' %>
      <% end %>
  </div>
</div> 
<%
=end%>

</br>
</br>

<h1>When to Eat</h1>

<br>
<%= week_calendar events: @recipes do |date, recipes| %>
  <%= date %>

  <% @recipes.each do |recipe| %>
    <div>
      <% if recipe.when == date %>
        <%= link_to recipe.name, recipe %>
      <% end %>
    </div>
  <% end %>
<% end %>

</br>

<h1>Shopping List</h1>
<% @recipes.each do |recipe| %>
  <% recipe.ingredients.each do |ingredient| %>
    <ul class="list-group">
       <li class="list-group-item">
        <% if ingredient.shopping == true %>
          <%="#{ingredient.qty} #{ingredient.unit} #{ingredient.name}" %>
        <% end %>
       </li>
    </ul>
  <% end %>
  <% end %>
<br>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path, :class => "btn btn-outline-success" %>

app/views/recipes/show.html.erb
<h2>Your recipe:</h2>

<p>
  
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @recipe.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= "#{@recipe.time} minutes "%>
</p>

<p>
  <strong>Date:</strong>
  <%= "#{@recipe.when}"%>
</p>


<%= link_to 'Edit Recipe', edit_recipe_path(@recipe), :class => "btn btn-outline-success" %> 
<br>
<br>

<div id="ingredients_wrapper">
 <h2>Ingredients:</h2>
 <%= render @recipe.ingredients %>
 <div id="form">
  <%= render "ingredients/form" %>
 </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, :class => "btn btn-outline-success" %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view,:class => "btn btn-outline-success" %>
  </div>

  <br>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>